#!/usr/bin/env python3
"""Explicit local UC transfer probe; never enables uploads in the player.

Requires a private request file generated by the opt-in Swift history resolver.
--allow-upload is permission for this invocation only. It pins the SDK limit to
16 KiB/s, caps its lifetime to 120 seconds and to 1% of the declared media size,
and exits the isolated SDK process even if native task cleanup hangs.
"""
import argparse
import ctypes as c
import hashlib
import json
import math
import os
from pathlib import Path
import subprocess
import sys
import threading
import tempfile
import time


class Init(c.Structure):
    _fields_ = [('app_id', c.c_char_p), ('version', c.c_char_p),
                ('config_path', c.c_char_p), ('save_tasks', c.c_uint8)]


class Create(c.Structure):
    _fields_ = [('save_path', c.c_char_p), ('save_name', c.c_char_p), ('url', c.c_char_p)]


class State(c.Structure):
    _fields_ = [('speed', c.c_uint64), ('total', c.c_uint64), ('downloaded', c.c_uint64),
                ('status', c.c_uint8), ('error', c.c_uint32), ('token_error', c.c_uint32)]


class Traffic(c.Structure):
    _fields_ = [('origin', c.c_uint64), ('p2p', c.c_uint64),
                ('p2s', c.c_uint64), ('dcdn', c.c_uint64)]


def emit(stage, **values):
    print(json.dumps({'stage': stage, **values}, sort_keys=True), flush=True)


def checked(code, operation):
    if code != 0:
        emit('sdk_failure', operation=operation, code=code)
        raise RuntimeError(operation)


def private_json(path):
    if path.is_symlink() or path.stat().st_mode & 0o077:
        raise ValueError('request_or_credentials_must_be_owner_only')
    return json.loads(path.read_text())


def worker(args):
    request = private_json(Path(args.request))
    credentials = private_json(Path.home() / 'Library/Application Support/NetVplayer/ThunderDownload/credentials.json')
    if credentials.get('issued_at', 0) + credentials.get('expires_in', 0) <= time.time() + 180:
        raise ValueError('login_token_needs_refresh')
    expected = int(request['expected_size'])
    # Conservative KiB bound, even if the SDK interprets KB as 1000 bytes.
    hard_seconds = min(120, math.floor(expected / 100 / (16 * 1024)))
    if args.allow_upload and hard_seconds < 10:
        raise ValueError('file_too_small_for_bounded_upload_test')
    duration = min(args.seconds, hard_seconds - 3) if args.allow_upload else args.seconds
    root = Path(args.output)
    root.mkdir(parents=True, exist_ok=True, mode=0o700)
    if not args.work_directory:
        raise ValueError('worker_requires_parent_owned_directory')
    state_dir = Path(args.work_directory)
    destination = state_dir / 'probe.mp4'
    if destination.exists():
        raise ValueError('probe_destination_already_exists')
    if (c.sizeof(Init), c.sizeof(Create), c.sizeof(State), c.sizeof(Traffic)) != (32, 24, 40, 32):
        raise ValueError('unsupported_native_ABI')
    sdk = c.CDLL(args.library)
    for name, argtypes in {
        'xl_dl_init': [c.POINTER(Init)],
        'xl_dl_login': [c.c_char_p, c.c_void_p],
        'xl_dl_create_p2sp_task': [c.POINTER(Create), c.POINTER(c.c_uint64)],
        'xl_dl_set_http_header': [c.c_uint64, c.c_char_p, c.c_char_p],
        'xl_dl_set_upload_switch': [c.c_uint32],
        'xl_dl_set_upload_speed_limit': [c.c_uint32],
        'xl_dl_set_dynamic_link_acceleration': [c.c_bool],
        'xl_dl_start_task': [c.c_uint64],
        'xl_dl_stop_task': [c.c_uint64],
        'xl_dl_delete_task': [c.c_uint64, c.c_uint8],
        'xl_dl_get_task_state': [c.c_uint64, c.POINTER(State)],
        'xl_dl_get_task_info': [c.c_uint64, c.c_char_p, c.c_void_p, c.POINTER(c.c_uint32)],
    }.items():
        fn = getattr(sdk, name)
        fn.argtypes = argtypes
        fn.restype = c.c_int32
    parameter = Init(credentials['app_id'].encode(), b'NetVplayer-Probe', str(state_dir).encode(), 0)
    checked(sdk.xl_dl_init(c.byref(parameter)), 'init')
    checked(sdk.xl_dl_set_upload_switch(0), 'upload_initially_off')
    checked(sdk.xl_dl_set_upload_speed_limit(16), 'upload_limit_16_KBps')
    session = c.create_string_buffer(4096)
    checked(sdk.xl_dl_login(credentials['login_token'].encode(), session), 'login')
    checked(sdk.xl_dl_set_dynamic_link_acceleration(True), 'dynamic_link_acceleration')
    task = c.c_uint64(0)
    create = Create(str(state_dir).encode(), b'probe.mp4', request['url'].encode())
    checked(sdk.xl_dl_create_p2sp_task(c.byref(create), c.byref(task)), 'create')
    for name, value in request['headers'].items():
        if name.lower() in ('cookie', 'origin', 'referer', 'user-agent'):
            checked(sdk.xl_dl_set_http_header(task.value, name.encode(), value.encode()), 'header')

    def deadline():
        # SDK process destruction terminates its upload workers even if the
        # native stop/off APIs hang. No settings persist into the player.
        emit('hard_deadline_process_exit', upload_enabled=False)
        os._exit(124)

    watchdog = threading.Timer(hard_seconds if args.allow_upload else duration + 10, deadline)
    watchdog.daemon = True
    watchdog.start()
    started = time.monotonic()
    completed = False
    last = State()
    last_traffic = Traffic()
    try:
        if args.allow_upload:
            checked(sdk.xl_dl_set_upload_switch(1), 'upload_on')
        checked(sdk.xl_dl_start_task(task.value), 'start')
        emit('started', upload_enabled=args.allow_upload, upload_limit_KBps=16,
             max_seconds=hard_seconds if args.allow_upload else 0,
             max_upload_bytes=16 * 1024 * hard_seconds if args.allow_upload else 0,
             max_upload_fraction=(16 * 1024 * hard_seconds / expected) if args.allow_upload else 0,
             expected_bytes=expected,
             resource_fingerprint=hashlib.sha256(request['url'].encode()).hexdigest()[:16])
        next_log = 0
        while time.monotonic() - started < duration:
            checked(sdk.xl_dl_get_task_state(task.value, c.byref(last)), 'state')
            elapsed = time.monotonic() - started
            if elapsed >= next_log:
                length = c.c_uint32(c.sizeof(Traffic))
                code = sdk.xl_dl_get_task_info(task.value, b'traffic', c.byref(last_traffic), c.byref(length))
                valid = code == 0 and length.value == c.sizeof(Traffic)
                emit('progress', elapsed=round(elapsed, 2), downloaded=last.downloaded,
                     speed_MiBps=round(last.speed / 1048576, 3), state=last.status,
                     task_error=last.error, token_error=last.token_error,
                     traffic_valid=valid, traffic_code=code,
                     **{name+'_bytes':getattr(last_traffic, name) if valid else None
                        for name, _ in Traffic._fields_})
                next_log = elapsed + 5
            if last.status == 8:
                completed = True
                break
            if last.status == 9 or last.token_error:
                raise RuntimeError('task_failed')
            time.sleep(0.25)
    finally:
        off = sdk.xl_dl_set_upload_switch(0)
        emit('upload_disabled', code=off)
        if off != 0:
            os._exit(125)
        stop = sdk.xl_dl_stop_task(task.value)
        deleted = sdk.xl_dl_delete_task(task.value, 1)
        emit('cleanup', stop_code=stop, delete_code=deleted)
        if destination.exists():
            destination.unlink()
    emit('finished', elapsed=round(time.monotonic()-started, 2), completed=completed,
         downloaded=last.downloaded, mean_MiBps=round(last.downloaded / max(1, time.monotonic()-started) / 1048576, 3))
    # No dlclose/uninit while SDK workers might still be executing.
    os._exit(0)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--request', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--library', default='/Applications/NetVplayer.app/Contents/Resources/ThunderDownloadSDK/libdk.dylib')
    parser.add_argument('--seconds', type=int, default=45, choices=range(10, 118), metavar='10..117')
    parser.add_argument('--allow-upload', action='store_true')
    parser.add_argument('--worker', action='store_true', help=argparse.SUPPRESS)
    parser.add_argument('--work-directory', help=argparse.SUPPRESS)
    args = parser.parse_args()
    os.umask(0o077)
    if args.worker:
        try:
            worker(args)
        except Exception as error:
            # Exceptions may contain signed URLs or credentials: type only.
            emit('failed', error_type=type(error).__name__)
            os._exit(1)
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True, mode=0o700)
    # Own all SDK state/sidecars and remove them only after native workers exit.
    # This also handles SDK .xltd files left after delete_task returns success.
    with tempfile.TemporaryDirectory(dir=output, prefix='sdk-probe-') as work:
        try:
            result = subprocess.run([
                sys.executable, __file__, *sys.argv[1:], '--worker', '--work-directory', work,
            ], timeout=180)
            return result.returncode
        except subprocess.TimeoutExpired:
            emit('child_terminated', reason='timeout')
            return 124


if __name__ == '__main__':
    sys.exit(main())
